### PR TITLE
Add autotag display to dashboard and fix bugs

### LINKED ISSUE #147: Autotag import not working correctly?
Discovered a mysterious issue where autotags (`SelectiveBookmarkTagger`s) that are imported from the Json file are not applied when bookmarks are added or edited. Taggers appear to be imported correctly, as `AutotagController#getTaggers()` shows the correct tag names and keywords for each tagger.

Newly-added autotags still work as expected, though.

### PR DESCRIPTION
**Pull request by dorcastan**
These are the main changes:
1. Add an autotag display to the Dashboard
    * Autotag names and conditions are shown in table form.
    * Might need to reposition it depending on where @Na-Nazhou puts the `Favorites` section.
2. Fix #147 (Autotag import bug)
    * Autotags were not imported properly as `toModelType()` was creating predicates with empty keyword lists, which always returned false.
3. Update JsonAdaptedBookmarkPredicate to include folder conditions

### CODE REVIEW

File: src/test/java/seedu/mark/model/predicates/BookmarkPredicateTest.java [hunk 1]
```diff
@@ -88,42 +100,71 @@ public void isEmpty() {
...
         BookmarkPredicate predicate = new BookmarkPredicate().withoutNameKeywords(KEYWORD_LIST_MULTIPLE);
+
+        // state check
         assertEquals(predicate.getNameKeywords(), new HashSet<>());
         assertEquals(predicate.getNotNameKeywords(), new HashSet<>(KEYWORD_LIST_MULTIPLE));
         assertEquals(predicate.getUrlKeywords(), new HashSet<>());
         assertEquals(predicate.getNotUrlKeywords(), new HashSet<>());
+
+        // behaviour check
+        // assumption: BookmarkBuilder.DEFAULT_NAME doesn't affect predicate result
```
Comment (TSAI-HSIAO-HAN) [inline src/test/java/seedu/mark/model/predicates/BookmarkPredicateTest.java]:
```suggestion
        // assumption: BookmarkBuilder.DEFAULT_URL doesn't affect predicate result
```

**Comment by dorcastan** [comment]
New Dashboard layout:

Screenshot 2019-11-06 at 10 38 40 PM

I put Reminders on top of Folders because I thought users might want to see reminders and favorites (important info) more frequently than folders/autotags.
