### PR TITLE
fix dry test bugs

### LINKED ISSUE #194: No function to view reminders
Steps to reproduce:
1. Add a reminder

2. Cannot view reminders. Where are the reminders displayed? There is no function to interact with it.

<hr><sub>[original: Nanosync/ped#14]<br/>
</sub>

### PR DESCRIPTION
**Pull request by TSAI-HSIAO-HAN**
fix #194 #178 
Also fix that the remind time should be after the current time.

### CODE REVIEW

File: src/main/java/seedu/mark/logic/commands/AddReminderCommand.java [hunk 1]
```diff
@@ -29,7 +29,8 @@
             + "[" + PREFIX_NOTE + "NOTE] \n"
             + "Example: " + COMMAND_WORD + " 1 "
             + PREFIX_TIME + "07/01/2020 1300 "
-            + PREFIX_NOTE + "Check the schedule ";
+            + PREFIX_NOTE + "Check the schedule \n"
+            + "You can find reminder in dashboard.";
```
Comment (openorclose) [inline src/main/java/seedu/mark/logic/commands/AddReminderCommand.java]:
```suggestion
            + "You can find your reminder in dashboard.";
```

File: src/main/java/seedu/mark/model/reminder/Reminder.java [hunk 2]
```diff
@@ -15,7 +15,7 @@
 public class Reminder {
 
     //TODO: temporarily; to change when confirmed
-    private static final String DATE_FORMATTER = "dd/MM/yyyy HHmm";
+    private static final String DATE_FORMATTER = "dd/MM/uuuu HHmm";
```
Comment (openorclose) [inline src/main/java/seedu/mark/model/reminder/Reminder.java]: Instead of have so many date formatters, can have all the other constants set to this one, so that don't have to repeat so many,

Comment (TSAI-HSIAO-HAN) [reply src/main/java/seedu/mark/model/reminder/Reminder.java]: I am thinking that the reminder only take the LocalDateTime object, so I leave the parsing part time string to parseUtil. (It also sound more reasonable)However, when generating the formatted time string, the reminder need to use the formatter again. I haven't decided where is the best place to put the formatter.

Comment (openorclose) [reply src/main/java/seedu/mark/model/reminder/Reminder.java]: yeah ok is just a small issue
